imports:
  - { resource: rest/services.rest.args.yaml }
  - { resource: rest/services.rest.req.yaml }

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  # Services
  service_min_count_symbols:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\MinCountSymbolsService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  service_min_price_symbols:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\MinPriceSymbolsService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  service_min_price_page:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\MinPricePageService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  service_min_count_page:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\MinCountPageService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  service_min_count_days_deadline:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\MinCountDaysDeadlineService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  service_single_spaced_coefficient:
    autowire: true
    class: Shayer\EduEssayPlugin\Service\CalcOption\SingleSpacedCoefficientService
    arguments:
      $option: '@Shayer\EduEssayPlugin\Common\Field\Option'

  # Register REST (v1)
  rest_min_count_symbols_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/minCountSymbolsOption'
      $method: 'POST'
      $callback: '@rest_min_count_symbols_request'
      $args: '@rest_min_count_symbols_args'

  rest_min_count_page_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/minCountPageOption'
      $method: 'POST'
      $callback: '@rest_min_count_page_request'
      $args: '@rest_min_count_page_args'

  rest_min_price_symbols_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/minPriceSymbolsOption'
      $method: 'POST'
      $callback: '@rest_min_price_symbols_request'
      $args: '@rest_min_price_symbols_args'

  rest_min_price_page_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/minPricePageOption'
      $method: 'POST'
      $callback: '@rest_min_price_page_request'
      $args: '@rest_min_price_page_args'


  rest_min_days_deadline_page_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/minCountDaysDeadlineOption'
      $method: 'POST'
      $callback: '@rest_min_count_days_deadline_request'
      $args: '@rest_min_count_days_deadline_args'

  rest_single_spaced_coefficient_option:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/singleSpacedCoefficientOption'
      $method: 'POST'
      $callback: '@rest_single_spaced_coefficient_request'
      $args: '@rest_single_spaced_coefficient_args'

  rest_variation_deadline:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/variationDeadline'
      $method: 'POST'
      $callback: '@variation_deadline_request'
      $args: '@rest_variation_deadline_args'

  rest_product_type_create:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/productType'
      $method: 'POST'
      $callback: '@product_type_create_request'
      $args: '@rest_product_type_create_args'

  rest_product_get_create:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'calcOptions/productType'
      $method: 'GET'
      $callback: '@product_type_get_request'
      $args: '@rest_product_type_get_args'

  rest_product_category_create:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'category/productCategory'
      $method: 'POST'
      $callback: '@product_category_create_request'
      $args: '@rest_product_category_create_args'

  rest_product_category_get:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'category/productCategory'
      $method: 'GET'
      $callback: '@product_category_get_request'
      $args: '@rest_product_category_get_args'

  rest_product_create:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'product'
      $method: 'POST'
      $callback: '@product_create_request'
      $args: '@rest_product_create_args'

  rest_product_get:
    autowire: true
    class: Shayer\EduEssayPlugin\Common\Registrar\RestApiRegistrar
    arguments:
      $routeNamespace: 'essay/v1'
      $route: 'product'
      $method: 'GET'
      $callback: '@product_get_request'
      $args: '@rest_product_get_args'
